# Generated by Django 4.2.3 on 2023-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
