# Generated by Django 4.2.3 on 2023-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofilemodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
