# Generated by Django 4.2.3 on 2023-07-31 08:37

import campstore.store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofilemodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[campstore.store.validators.validate_name, campstore.store.validators.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[campstore.store.validators.validate_name, campstore.store.validators.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[campstore.store.validators.validate_phone_number]),
        ),
    ]
