# Generated by Django 4.2.3 on 2023-07-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress_name',
            new_name='address_name',
        ),
    ]
