# Generated by Django 4.2.3 on 2023-07-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_adress_name_order_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_name',
            new_name='address',
        ),
    ]
