# Generated by Django 4.2.3 on 2023-07-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zipcode',
            new_name='post_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
