# Generated by Django 4.2.3 on 2023-07-31 07:45

import campstore.store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[campstore.store.validators.validate_positive_number]),
        ),
    ]
