# Generated by Django 4.2.3 on 2023-07-31 08:37

import campstore.store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, validators=[campstore.store.validators.validate_name, campstore.store.validators.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, validators=[campstore.store.validators.validate_name, campstore.store.validators.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[campstore.store.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[campstore.store.validators.validate_positive_number]),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, validators=[campstore.store.validators.validate_name, campstore.store.validators.validate_name_length]),
        ),
    ]
