# Generated by Django 4.2.3 on 2023-07-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
