# Generated by Django 4.2.3 on 2023-08-02 11:38

import campstore.store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[campstore.store.validators.validate_positive_number]),
        ),
    ]
