# Generated by Django 4.2.3 on 2023-08-10 08:09

import campstore.store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, validators=[campstore.store.validators.validate_name_length]),
        ),
    ]
